replicaCount: 1

image:
    repository: richardprax/devops-github-frontend
    tag: latest
    pullPolicy: IfNotPresent

service:
    type: ClusterIP
    port: 3000

ingress:
    enabled: true
    host: frontend.local
    path: /
