name: Backend CI

on:
    push:
        branches: [dev]
        paths: [backEnd/**]
    pull_request:
        paths: [backEnd/**]

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                  java-version: "21"
                  distribution: "temurin"

            - name: Make Maven Wrapper Executable
              run: chmod +x mvnw
              working-directory: backEnd

    test:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                  java-version: "21"
                  distribution: "temurin"

            - name: Run Tests with Coverage
              run: ./mvnw clean verify
              working-directory: backEnd

            - name: Upload JUnit Test Results
              uses: actions/upload-artifact@v4
              with:
                  name: junit-results
                  path: backEnd/target/surefire-reports/

            - name: Upload Cobertura Coverage Report
              uses: actions/upload-artifact@v4
              with:
                  name: cobertura-coverage
                  path: backEnd/target/site/jacoco/jacoco.xml

    lint:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                  java-version: "21"
                  distribution: "temurin"

            - name: Run Checkstyle
              run: ./mvnw checkstyle:check
              working-directory: backEnd

            - name: Upload Checkstyle XML
              uses: actions/upload-artifact@v4
              with:
                  name: checkstyle-xml
                  path: backEnd/target/checkstyle-result.xml

    build:
        runs-on: ubuntu-latest
        needs: [test, lint]
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                  java-version: "21"
                  distribution: "temurin"

            - name: Build without tests
              run: ./mvnw clean package -DskipTests
              working-directory: backEnd

            - name: Upload Built JAR
              uses: actions/upload-artifact@v4
              with:
                  name: backend-jar
                  path: backEnd/target/*.jar
