name: Backend CI

on:
    push:
        branches: [dev]
        paths: [backEnd/**]
    pull_request:
        paths: [backEnd/**]

jobs:
    test-lint-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backEnd

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                  java-version: "21"
                  distribution: "temurin"

            - name: Make Maven Wrapper Executable
              run: chmod +x mvnw

            - name: Run Unit Tests
              run: ./mvnw test

            - name: Generate HTML Report
              run: ./mvnw surefire-report:report

            - name: Upload Test Report (Surefire XML)
              uses: actions/upload-artifact@v4
              with:
                  name: surefire-xml
                  path: backEnd/target/surefire-reports/

            - name: Upload Test HTML Report
              uses: actions/upload-artifact@v4
              with:
                  name: test-report-html
                  path: backEnd/target/site/surefire-report.html

            - name: Run Build
              run: ./mvnw clean package -DskipTests

            - name: Upload Built JAR
              uses: actions/upload-artifact@v4
              with:
                  name: backend-jar
                  path: backEnd/target/*.jar
