name: Backend CI

on:
  push:
    branches: [dev]
    paths: [backEnd/**]
  pull_request:
    paths: [backEnd/**]

jobs:
  test-lint-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backEnd

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Make Maven Wrapper Executable
        run: chmod +x mvnw

      - name: Run Linter (Checkstyle)
        run: ./mvnw checkstyle:check

      - name: Run Unit Tests
        run: ./mvnw test

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: surefire-report
          path: backEnd/target/surefire-reports/

      - name: Run Build
        run: ./mvnw clean package -DskipTests

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: backEnd/target/*.jar
