name: Frontend CI

on: [push]
# TODO: activate this when the pipeline is ready
#    push:
#        branches: [dev]
#        paths: [frontEnd/**]
#    pull_request:
#        paths: [frontEnd/**]

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install Dependencies
              run: npm ci
              working-directory: frontend

    test:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install Dependencies
              run: npm ci
              working-directory: frontend

            - name: Run Tests with Coverage
              run: npm run test
              working-directory: frontend

            - name: Upload JUnit Test Results
              uses: actions/upload-artifact@v4
              with:
                  name: frontend-junit-results
                  path: frontend/reports/junit/

            - name: Upload Coverage Report
              uses: actions/upload-artifact@v4
              with:
                  name: frontend-coverage
                  path: frontend/coverage/

    lint:
        runs-on: ubuntu-latest
        needs: setup
        continue-on-error: true # Diese Zeile sorgt dafür, dass der Job fortgesetzt wird, auch wenn ESLint Fehler hat
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install Dependencies
              run: npm ci
              working-directory: frontend

            - name: Run ESLint
              run: |
                  npx eslint . --ext .js,.jsx,.ts,.tsx -f json -o eslint-report.json
              working-directory: frontend

            - name: Upload ESLint Report
              uses: actions/upload-artifact@v4
              with:
                  name: eslint-report
                  path: frontend/eslint-report.json

    build:
        runs-on: ubuntu-latest
        needs: [test, lint]
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install Dependencies
              run: npm ci
              working-directory: frontend

            - name: Build Next.js App
              run: npm run build
              working-directory: frontend

            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: frontend-build
                  path: frontend/.next/
