name: Full Stack CD

on:
    workflow_run:
        workflows: ["Full Stack CI"]
        types:
            - completed

jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            - name: Set version from CI
              # Hier nehmen wir die Commit SHA aus der CI Pipeline als Version
              run: echo "VERSION=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_ENV

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Start PostgreSQL Database
              run: |
                  docker run -d --name postgres-db -p 5432:5432 \
                    -e POSTGRES_DB=koerperschmiede \
                    -e POSTGRES_USER=admin \
                    -e POSTGRES_PASSWORD=admin \
                    postgres:15.3

            - name: Start Backend Container
              run: |
                  docker run -d --name backend-container -p 8080:8080 \
                    -e SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/koerperschmiede \
                    -e SPRING_DATASOURCE_USERNAME=admin \
                    -e SPRING_DATASOURCE_PASSWORD=admin \
                    ${{ secrets.DOCKER_USERNAME }}/devops-github-backend:${{ env.VERSION }}

            - name: Start Frontend Container
              run: |
                  docker run -d --name frontend-container -p 3000:3000 \
                    -e NEXT_PUBLIC_API_URL=http://host.docker.internal:8080 \
                    ${{ secrets.DOCKER_USERNAME }}/devops-github-frontend:${{ env.VERSION }}

            - name: Wait for backend to be healthy
              run: |
                  for i in {1..30}; do
                    if curl -s http://localhost:8080/actuator/health | grep '"status":"UP"'; then
                      echo "Backend is healthy"
                      break
                    else
                      echo "Waiting for backend..."
                      sleep 5
                    fi
                  done

            - name: Check frontend
              run: |
                  if curl -s http://localhost:3000 | grep "<!DOCTYPE html>"; then
                    echo "Frontend is running"
                  else
                    echo "Frontend is not responding"
                    exit 1
                  fi
